Bug fix: Fixed a bug wherein the install script was exiting with the incorrect status code on failure.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -61,6 +61,9 @@ install_tmux() {
     make -j $concurrency
     if [[ $? -eq 0 ]]; then
       make install
+    else
+        echo "Failed to install tmux ${version}"
+        exit 2
     fi
   )
 }
@@ -86,6 +89,7 @@ install_libevent() {
   if [[ $? -eq 0 ]]; then
     make install
   else
+    echo "Failed to install libevent ${libevent_version}"
     exit 2
   fi
 }
